spring.application.name=login-seguro

spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=loginseguro
spring.data.mongodb.auto-index-creation=true

spring.session.mongodb.collection-name=sessoes
server.servlet.session.timeout=30m

spring.thymeleaf.cache=false

app.nome=Login Seguro
app.tema=padrao
app.admin.email=${ADMIN_EMAIL:admin@loginseguro.com}
app.admin.senha=${ADMIN_SENHA}
